'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useDeployment } from '@/lib/context/DeploymentContext';
import { generateResourceConfig } from '@/lib/utils/configGenerator';
import { ResourceConfig } from '@/lib/context/DeploymentContext';

export default function Resources() {
  const router = useRouter();
  const { state, updateResources, updateEnvironment, updateContainer } = useDeployment();
  
  const [config, setConfig] = useState<ResourceConfig | null>(null);
  const [expandedContainers, setExpandedContainers] = useState<Set<string>>(new Set());
  const [hasVolume, setHasVolume] = useState(false);
  const [volumeConfig, setVolumeConfig] = useState({
    mountPath: '/app/data',
    sizeGB: 50,
    autoScale: true,
    backupFrequency: 'disabled' as 'disabled' | 'hourly' | 'daily' | 'weekly',
    deleteWithContainer: false
  });

  // Scroll to top on mount, or to hash target if present
  useEffect(() => {
    const hash = window.location.hash;
    if (hash) {
      // Wait a bit for the page to render
      setTimeout(() => {
        const element = document.querySelector(hash);
        if (element) {
          element.scrollIntoView({ behavior: 'smooth', block: 'start' });
          // Add a highlight effect
          element.classList.add('ring-2', 'ring-purple-500', 'ring-offset-2');
          setTimeout(() => {
            element.classList.remove('ring-2', 'ring-purple-500', 'ring-offset-2');
          }, 2000);
        }
      }, 300);
    } else {
      window.scrollTo(0, 0);
    }
  }, []);

  // Generate intelligent defaults on mount
  useEffect(() => {
    if (state.questionnaire) {
      const generatedConfig = generateResourceConfig(state.questionnaire);
      setConfig(generatedConfig);
      
      // Expand first container by default
      if (state.containers.length > 0) {
        setExpandedContainers(new Set([state.containers[0].id]));
      }
    } else {
      // If no questionnaire data, redirect to start
      router.push('/');
    }
  }, [state.questionnaire, router]);

  const toggleContainer = (containerId: string) => {
    setExpandedContainers(prev => {
      const newSet = new Set(prev);
      if (newSet.has(containerId)) {
        newSet.delete(containerId);
      } else {
        newSet.add(containerId);
      }
      return newSet;
    });
  };

  const updateContainerResource = (containerId: string, field: string, value: any) => {
    const container = state.containers.find(c => c.id === containerId);
    if (!container) return;

    if (field.startsWith('resources.')) {
      const resourceField = field.split('.')[1];
      if (resourceField === 'replicas') {
        updateContainer(containerId, {
          resources: {
            ...container.resources,
            replicas: value
          }
        });
      } else {
        updateContainer(containerId, {
          resources: {
            ...container.resources,
            [resourceField]: value
          }
        });
      }
    } else if (field.startsWith('healthCheck.')) {
      const healthField = field.split('.')[1];
      updateContainer(containerId, {
        healthCheck: {
          ...container.healthCheck,
          [healthField]: value
        }
      });
    } else if (field === 'serviceAccess') {
      updateContainer(containerId, { serviceAccess: value });
    } else {
      updateContainer(containerId, { [field]: value });
    }
  };

  const addEnvironmentVariable = (containerId: string) => {
    const container = state.containers.find(c => c.id === containerId);
    if (!container) return;
    
    updateContainer(containerId, {
      environmentVariables: [...container.environmentVariables, { key: '', value: '', masked: false }]
    });
  };

  const updateEnvironmentVariable = (containerId: string, index: number, field: 'key' | 'value' | 'masked', value: string | boolean) => {
    const container = state.containers.find(c => c.id === containerId);
    if (!container) return;
    
    const updated = [...container.environmentVariables];
    updated[index] = { ...updated[index], [field]: value };
    updateContainer(containerId, { environmentVariables: updated });
  };

  const removeEnvironmentVariable = (containerId: string, index: number) => {
    const container = state.containers.find(c => c.id === containerId);
    if (!container) return;
    
    updateContainer(containerId, {
      environmentVariables: container.environmentVariables.filter((_, i) => i !== index)
    });
  };

  const handleContinue = () => {
    if (config) {
      updateResources(config);
      
      // Auto-generate environment variables based on selected resources
      const autoGenerated: { key: string; value: string; readOnly: boolean }[] = [];
      
      // Generate realistic random values
      const dbPassword = `${Math.random().toString(36).substring(2, 10)}${Math.random().toString(36).substring(2, 10)}`.toUpperCase();
      const redisPassword = `${Math.random().toString(36).substring(2, 12)}${Math.random().toString(36).substring(2, 12)}`.toUpperCase();
      const dbHost = `db-${Math.random().toString(36).substring(2, 9)}.unhazzle.io`;
      const cacheHost = `cache-${Math.random().toString(36).substring(2, 9)}.unhazzle.io`;

      // Add database credentials if database is configured
      if (config.database) {
        autoGenerated.push({
          key: 'DATABASE_URL',
          value: `postgresql://unhazzle_user:${dbPassword}@${dbHost}:5432/${state.questionnaire?.appType || 'app'}_prod`,
          readOnly: true
        });
        autoGenerated.push({
          key: 'DATABASE_PASSWORD',
          value: dbPassword,
          readOnly: true
        });
      }

      // Add cache credentials if Redis is configured
      if (config.cache) {
        autoGenerated.push({
          key: 'REDIS_URL',
          value: `redis://default:${redisPassword}@${cacheHost}:6379`,
          readOnly: true
        });
        autoGenerated.push({
          key: 'REDIS_PASSWORD',
          value: redisPassword,
          readOnly: true
        });
      }
      
      // Save environment variables with empty user secrets
      updateEnvironment({
        autoGenerated,
        userSecrets: []
      });
      
      // Update container with volume configuration if enabled
      if (hasVolume && state.containers.length > 0) {
        const mainContainer = state.containers[0];
        updateContainer(mainContainer.id, {
          volume: volumeConfig
        });
      }
      
      router.push('/domain');
    }
  };

  if (!config) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto mb-4"></div>
          <p className="text-slate-600">Generating intelligent configuration...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 py-12 px-4">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-medium mb-4">
            <span>✨</span>
            <span>Smart defaults configured • {state.containers.length} container{state.containers.length > 1 ? 's' : ''} selected</span>
          </div>
          <h1 className="text-4xl font-bold text-slate-900 mb-3">
            Configure Container Resources
          </h1>
          <p className="text-lg text-slate-600">
            Set resources, health checks, and environment variables for each container
          </p>
        </div>

        {/* Container Configuration Sections */}
        {state.containers.length === 0 ? (
          <div className="bg-white rounded-2xl shadow-lg p-12 mb-6 text-center">
            <div className="text-6xl mb-4">📦</div>
            <h2 className="text-2xl font-bold text-slate-900 mb-2">No Containers Selected</h2>
            <p className="text-slate-600 mb-6">Please go back and select at least one container image</p>
            <button
              onClick={() => router.back()}
              className="px-6 py-3 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 transition"
            >
              ← Back to Application
            </button>
          </div>
        ) : (
          <div className="space-y-4 mb-6">
            {state.containers.map((container, index) => {
              const isExpanded = expandedContainers.has(container.id);
              const displayName = container.imageUrl.split('/').pop() || `Container ${index + 1}`;
              
              return (
                <div key={container.id} id="application" className="bg-white rounded-2xl shadow-lg overflow-hidden">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-gradient-to-br from-purple-600 to-blue-600 rounded-lg flex items-center justify-center text-white text-xl">
                🚀
              </div>
              <div>
                <h2 className="text-2xl font-bold text-slate-900">Application Resources</h2>
                <p className="text-sm text-slate-600">Container compute and scaling</p>
              </div>
            </div>
            <div className="text-xs bg-purple-100 text-purple-700 px-3 py-1 rounded-full font-semibold">
              AUTO-CONFIGURED
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {/* Replicas */}
            <div className="border border-slate-200 rounded-lg p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-2xl">📊</span>
                <h3 className="font-semibold text-slate-900">Auto-scaling</h3>
              </div>
              <div className="space-y-2">
                <div>
                  <label className="text-xs text-slate-600">Min replicas</label>
                  <input
                    type="number"
                    value={config.replicas.min}
                    onChange={(e) => setConfig({...config, replicas: {...config.replicas, min: parseInt(e.target.value)}})}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg mt-1 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                    min="1"
                    max="10"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-600">Max replicas</label>
                  <input
                    type="number"
                    value={config.replicas.max}
                    onChange={(e) => setConfig({...config, replicas: {...config.replicas, max: parseInt(e.target.value)}})}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg mt-1 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                    min="1"
                    max="20"
                  />
                </div>
              </div>
              <p className="text-xs text-slate-500 mt-3">
                💡 Scales automatically based on CPU usage
              </p>
            </div>

            {/* CPU */}
            <div className="border border-slate-200 rounded-lg p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-2xl">⚡</span>
                <h3 className="font-semibold text-slate-900">CPU</h3>
              </div>
              <div>
                <label className="text-xs text-slate-600">Per replica</label>
                <select
                  value={config.cpu}
                  onChange={(e) => setConfig({...config, cpu: e.target.value})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg mt-1 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="0.5 vCPU">0.5 vCPU</option>
                  <option value="1 vCPU">1 vCPU</option>
                  <option value="2 vCPU">2 vCPU</option>
                  <option value="4 vCPU">4 vCPU</option>
                </select>
              </div>
              <p className="text-xs text-slate-500 mt-3">
                💡 {state.questionnaire?.traffic === 'burst' ? 'Higher CPU for burst traffic' : 'Standard for steady traffic'}
              </p>
            </div>

            {/* Memory */}
            <div className="border border-slate-200 rounded-lg p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-2xl">💾</span>
                <h3 className="font-semibold text-slate-900">Memory</h3>
              </div>
              <div>
                <label className="text-xs text-slate-600">Per replica</label>
                <select
                  value={config.memory}
                  onChange={(e) => setConfig({...config, memory: e.target.value})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg mt-1 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="512MB">512MB</option>
                  <option value="1GB">1GB</option>
                  <option value="2GB">2GB</option>
                  <option value="4GB">4GB</option>
                  <option value="8GB">8GB</option>
                </select>
              </div>
              <p className="text-xs text-slate-500 mt-3">
                💡 Sufficient for Node/Python apps with DB connections
              </p>
            </div>
          </div>

          {/* Application Volume (Optional) */}
          <div className="mt-6 pt-6 border-t border-slate-200">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <span className="text-xl">💾</span>
                <h3 className="font-semibold text-slate-900">Persistent Storage (Optional)</h3>
              </div>
              {!hasVolume && (
                <button
                  onClick={() => setHasVolume(true)}
                  className="text-sm px-3 py-1 bg-purple-50 text-purple-700 rounded-lg hover:bg-purple-100 transition font-medium"
                >
                  + Add Volume
                </button>
              )}
              {hasVolume && (
                <button
                  onClick={() => setHasVolume(false)}
                  className="text-sm px-3 py-1 text-slate-600 hover:text-red-600 transition font-medium"
                >
                  Remove
                </button>
              )}
            </div>

            {!hasVolume ? (
              <p className="text-sm text-slate-500">
                💡 Add persistent storage for user uploads, logs, or application data
              </p>
            ) : (
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-slate-600 font-medium block mb-1">Mount Path</label>
                  <input
                    type="text"
                    value={volumeConfig.mountPath}
                    onChange={(e) => setVolumeConfig({...volumeConfig, mountPath: e.target.value})}
                    placeholder="/app/data"
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none font-mono"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-600 font-medium block mb-1">
                    Size (GB) • €{(volumeConfig.sizeGB * 0.044).toFixed(2)}/mo
                  </label>
                  <input
                    type="number"
                    value={volumeConfig.sizeGB}
                    onChange={(e) => setVolumeConfig({...volumeConfig, sizeGB: parseInt(e.target.value) || 50})}
                    min="10"
                    max="500"
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                  />
                </div>
                <div className="md:col-span-2">
                  <label className="flex items-center gap-2 cursor-pointer text-sm">
                    <input
                      type="checkbox"
                      checked={volumeConfig.autoScale}
                      onChange={(e) => setVolumeConfig({...volumeConfig, autoScale: e.target.checked})}
                      className="w-4 h-4 rounded border-slate-300 text-purple-600 focus:ring-purple-500"
                    />
                    <span className="text-slate-700">Auto-expand when 80% full</span>
                  </label>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Database Configuration */}
        {config.database && (
          <div id="database" className="bg-white rounded-2xl shadow-lg p-8 mb-6">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-green-600 to-teal-600 rounded-lg flex items-center justify-center text-white text-xl">
                  🐘
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-slate-900">
                    Database ({config.database.engine.toUpperCase()})
                  </h2>
                  <p className="text-sm text-slate-600">Persistent storage with automatic backups</p>
                </div>
              </div>
              <div className="text-xs bg-green-100 text-green-700 px-3 py-1 rounded-full font-semibold">
                RECOMMENDED
              </div>
            </div>

            <div className="grid md:grid-cols-4 gap-6 mb-6">
              {/* CPU */}
              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">⚡</span>
                  <h3 className="font-semibold text-slate-900">CPU</h3>
                </div>
                <select
                  value={config.database.cpu || '2 vCPU'}
                  onChange={(e) => setConfig({...config, database: config.database ? {...config.database, cpu: e.target.value} : undefined})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="1 vCPU">1 vCPU</option>
                  <option value="2 vCPU">2 vCPU</option>
                  <option value="4 vCPU">4 vCPU</option>
                  <option value="8 vCPU">8 vCPU</option>
                </select>
                <p className="text-xs text-slate-500 mt-3">
                  💡 Dedicated CPU cores
                </p>
              </div>

              {/* Memory */}
              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">💾</span>
                  <h3 className="font-semibold text-slate-900">Memory</h3>
                </div>
                <select
                  value={config.database.memory || '4GB'}
                  onChange={(e) => setConfig({...config, database: config.database ? {...config.database, memory: e.target.value} : undefined})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="2GB">2GB</option>
                  <option value="4GB">4GB</option>
                  <option value="8GB">8GB</option>
                  <option value="16GB">16GB</option>
                  <option value="32GB">32GB</option>
                </select>
                <p className="text-xs text-slate-500 mt-3">
                  💡 For query caching
                </p>
              </div>

              {/* Storage */}
              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">💿</span>
                  <h3 className="font-semibold text-slate-900">Storage</h3>
                </div>
                <select
                  value={config.database.storage}
                  onChange={(e) => setConfig({...config, database: config.database ? {...config.database, storage: e.target.value} : undefined})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="10GB">10GB</option>
                  <option value="20GB">20GB</option>
                  <option value="50GB">50GB</option>
                  <option value="100GB">100GB</option>
                  <option value="200GB">200GB</option>
                  <option value="500GB">500GB</option>
                  <option value="1TB">1TB</option>
                </select>
                <p className="text-xs text-slate-500 mt-3">
                  💡 Database disk space
                </p>
              </div>

              {/* Backup Retention */}
              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">🔄</span>
                  <h3 className="font-semibold text-slate-900">Backups</h3>
                </div>
                <select
                  value={config.database.backups.retention}
                  onChange={(e) => setConfig({
                    ...config, 
                    database: config.database ? {
                      ...config.database, 
                      backups: {...config.database.backups, retention: e.target.value}
                    } : undefined
                  })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="3 days">3 days</option>
                  <option value="7 days">7 days</option>
                  <option value="14 days">14 days</option>
                  <option value="30 days">30 days</option>
                </select>
                <p className="text-xs text-slate-500 mt-3">
                  💡 Daily backups at 2 AM UTC
                </p>
              </div>
            </div>

            <div className="mt-4 p-4 bg-green-50 border border-green-200 rounded-lg">
              <p className="text-sm text-green-800">
                <strong>✓ Included:</strong> High availability standby, automated failover, encryption at rest
              </p>
            </div>
          </div>
        )}

        {/* Cache Configuration */}
        {config.cache && (
          <div id="cache" className="bg-white rounded-2xl shadow-lg p-8 mb-6">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-red-600 to-orange-600 rounded-lg flex items-center justify-center text-white text-xl">
                  ⚡
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-slate-900">
                    Cache ({config.cache.engine})
                  </h2>
                  <p className="text-sm text-slate-600">High-speed in-memory storage</p>
                </div>
              </div>
              <div className="text-xs bg-orange-100 text-orange-700 px-3 py-1 rounded-full font-semibold">
                E-COMMERCE
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">💨</span>
                  <h3 className="font-semibold text-slate-900">Memory</h3>
                </div>
                <select
                  value={config.cache.memory}
                  onChange={(e) => setConfig({...config, cache: config.cache ? {...config.cache, memory: e.target.value} : undefined})}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none"
                >
                  <option value="256MB">256MB</option>
                  <option value="512MB">512MB</option>
                  <option value="1GB">1GB</option>
                  <option value="2GB">2GB</option>
                  <option value="4GB">4GB</option>
                </select>
                <p className="text-xs text-slate-500 mt-3">
                  💡 For sessions, product data, and API responses
                </p>
              </div>

              <div className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">💾</span>
                  <h3 className="font-semibold text-slate-900">Persistence</h3>
                </div>
                <div className="px-3 py-2 bg-slate-100 rounded-lg border border-slate-200">
                  <p className="text-sm text-slate-700">{config.cache.persistence}</p>
                </div>
                <p className="text-xs text-slate-500 mt-3">
                  💡 {config.cache.persistence !== 'None' ? 'Survives restarts' : 'In-memory only'}
                </p>
              </div>
            </div>

            <div className="mt-4 p-4 bg-orange-50 border border-orange-200 rounded-lg">
              <p className="text-sm text-orange-800">
                <strong>Use cases:</strong> Session storage, shopping carts, product catalogs, rate limiting
              </p>
            </div>
          </div>
        )}

        {/* Why These Defaults */}
        <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl p-6 mb-8 border border-purple-100">
          <h3 className="font-semibold text-slate-900 mb-3 flex items-center gap-2">
            <span>💡</span>
            <span>Why we chose these defaults:</span>
          </h3>
          <ul className="space-y-2 text-sm text-slate-700">
            <li className="flex items-start gap-2">
              <span className="text-purple-600 mt-0.5">•</span>
              <span><strong>2-10 replicas:</strong> Your "burst traffic" pattern needs aggressive scaling for flash sales</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-purple-600 mt-0.5">•</span>
              <span><strong>{config.cpu} & {config.memory}:</strong> Handles e-commerce workloads with DB connections and API calls</span>
            </li>
            {config.database && (
              <li className="flex items-start gap-2">
                <span className="text-purple-600 mt-0.5">•</span>
                <span><strong>{config.database.storage} storage:</strong> Sufficient for early-stage e-commerce (thousands of products)</span>
              </li>
            )}
            {config.cache && (
              <li className="flex items-start gap-2">
                <span className="text-purple-600 mt-0.5">•</span>
                <span><strong>{config.cache.memory} cache:</strong> Optimized for session storage and product catalog caching</span>
              </li>
            )}
          </ul>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between">
          <button
            onClick={() => router.back()}
            className="px-6 py-3 text-slate-600 hover:text-slate-900 font-medium transition"
          >
            ← Back
          </button>
          <button
            onClick={handleContinue}
            className="inline-flex items-center gap-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold px-8 py-3 rounded-lg hover:from-purple-700 hover:to-blue-700 transition-all transform hover:scale-105 shadow-lg"
          >
            <span>Continue to Domain Setup</span>
            <span>→</span>
          </button>
        </div>
      </div>
    </div>
  );
}
