name: Deploy Website & Prototype to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: prototype-app/package-lock.json

      - name: Create deployment directory
        run: mkdir -p deploy

      - name: Copy marketing website to deploy directory
        run: |
          cp index.html deploy/
          cp styles.css deploy/
          cp script.js deploy/
          cp favicon.ico deploy/ 2>/dev/null || true
          cp *.svg deploy/ 2>/dev/null || true

      - name: Install prototype-app dependencies
        working-directory: prototype-app
        run: npm ci

      - name: Build prototype-app
        working-directory: prototype-app
        run: npm run build

      - name: Copy prototype-app build to deploy directory
        run: cp -r prototype-app/out deploy/unhazzle.io

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

